# 每日任务

名称： 哔哩哔哩-每日任务


在：
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron： '0 16 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（16+8=24点整）
    # 建议每个人通过设置名称为 Production 的 GitHub Environments 来设定为自己的目标运行时间（详细设置方法见文档说明）

环境：
  ASPNETCORE_ENVIRONMENT: ${{secrets. ENV}} # 运行环境
  Ray_BiliBiliCookies__1： ${{secrets.COOKIESTR}}
  Ray_BiliBiliCookies__2： ${{secrets.饼干STR2}}
  Ray_BiliBiliCookies__3： ${{secrets.饼干STR3}}
  # 推送：
  Ray_Serilog__WriteTo__3__Args__botToken： ${{secrets.PUSHTGTOKEN}} # Telegram
  Ray_Serilog__WriteTo__3__Args__chatId： ${{secrets.PUSHTGCHATID}}
  Ray_Serilog__WriteTo__3__Args__restrictedToMinimumLevel： ${{secrets.PUSHTGLEVEL}}
  Ray_Serilog__WriteTo__4__Args__webHookUrl: ${{secrets. PUSHWEIXINURL}} # 企业微信
  Ray_Serilog__WriteTo__4__Args__restrictedToMinimumLevel： ${{secrets.普威新级}}
  Ray_Serilog__WriteTo__5__Args__webHookUrl： ${{secrets.PUSHDINGURL}} # 钉钉
  Ray_Serilog__WriteTo__5__Args__restrictedToMinimumLevel： ${{secrets.PUSHDINGLEVEL}}
  Ray_Serilog__WriteTo__6__Args__scKey： ${{secrets.PUSHSCKEY}} # Server酱
  Ray_Serilog__WriteTo__6__Args__turboScKey： ${{secrets.PUSHSERVERTSCKEY}}
  Ray_Serilog__WriteTo__6__Args__restrictedToMinimumLevel： ${{secrets.PUSHSERVERLEVEL}}
  Ray_Serilog__WriteTo__7__Args__sKey: ${{secrets. PUSHCOOLSKEY}} # 酷推
  Ray_Serilog__WriteTo__7__Args__restrictedToMinimumLevel： ${{secrets.PUSHCOOLLEVEL}}
  Ray_Serilog__WriteTo__8__Args__api: ${{secrets. PUSHOTHERAPI}} # 自定义api
  Ray_Serilog__WriteTo__8__Args__placeholder： ${{secrets.PUSHOTHERPLACEHOLDER}}
  Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate： ${{secrets.PUSHOTHERBODYJSONTEMPLATE}}
  Ray_Serilog__WriteTo__8__Args__restrictedToMinimumLevel： ${{secrets.PUSHOTHERLEVEL}}
  Ray_Serilog__WriteTo__9__Args__token： ${{secrets.PUSHPLUSTOKEN}} # PushPlus
  Ray_Serilog__WriteTo__9__Args__topic： ${{secrets.PUSHPLUSTOPIC}}
  Ray_Serilog__WriteTo__9__Args__channel： ${{secrets.普加渠道}}
  Ray_Serilog__WriteTo__9__Args__webhook： ${{secrets.PUSHPLUSWEBHOOK}}
  Ray_Serilog__WriteTo__9__Args__restrictedToMinimumLevel： ${{secrets.PUSHPLUSLEVEL}}
  # 安全相关：
  Ray_Security__IsSkipDailyTask： ${{secrets.ISSKIPDAILYTASK}}
  Ray_Security__IntervalSecondsBetweenRequestApi： ${{secrets.INTERVALSECONDSBETWEENREQUESTAPI}}
  Ray_Security__IntervalMethodTypes： ${{secrets.间隔方法型}}
  Ray_Security__UserAgent： ${{secrets.用户代理}}
  Ray_Security__WebProxy： ${{secrets.WEBPROXY}}
  Ray_Security__RandomSleepMaxMin： ${{secrets.随机睡眠最大分钟}}
  # 每日任务：
  Ray_DailyTaskConfig__NumberOfCoins： ${{secrets.币数}}
  Ray_DailyTaskConfig__SelectLike： ${{secrets.选择类}}
  Ray_DailyTaskConfig__SupportUpIds： ${{secrets.支持UPIDS}}
  Ray_DailyTaskConfig__DayOfAutoCharge： ${{secrets.天奥夫汽车}}
  Ray_DailyTaskConfig__AutoChargeUpId： ${{secrets.自动充电}}
  Ray_DailyTaskConfig__ChargeComment： ${{secrets.收费评论}}
  Ray_DailyTaskConfig__DayOfReceiveVipPrivilege： ${{secrets.DAYOFREREIVEVIPPRIVILEGE}}
  Ray_DailyTaskConfig__DayOfExchangeSilver2Coin： ${{secrets.DAYOFEXCHANGESILVER2COIN}}
  Ray_DailyTaskConfig__DevicePlatform： ${{secrets.设备平台}}
  Ray_Serilog__WriteTo__0__Args__restrictedToMinimumLevel： ${{secrets.CONSOLELOGLEVEL}}
  Ray_Serilog__WriteTo__0__Args__outputTemplate： ${{secrets.控制台日志模板}} 

招聘职位：

  预检查：
    运行 on： ubuntu-latest
    输出：
      result: ${{ steps.check.outputs.result }} # 不能直接传递secrets的值，否则会被skip，需要转一下
    步骤：
    - id： 检查
      如果： env.是开放每日任务=='真'
      运行： |
echo “：：set-output name=result：：开启”
  运行-每日-任务：

    运行 on： ubuntu-latest
    环境：生产
    需求：预检查
    if： needs.pre-check.outputs.result=='开启'

    步骤：

    # 设置服务器时区为东八区 
    - 名称：设置时区
      运行： sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - 名称： 结账
      用途： 操作/checkout@v2
      
    # .Net 环境
    - 名称： 安装程序 .NET
      用途： 操作/设置dotnet@v1
      与：
        点网版本： 6.0.x
 
    # 测试运行
    - 名称：测试应用
      运行： |
cd ./src/Ray.BiliBiliTool.Console
dotnet run --runTasks=Daily
